# Generated by Django 5.0.14 on 2026-07-18 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(choices=[('groq', 'GROQ_API_KEY'), ('tavily', 'TAVILY_API_KEY'), ('google', 'GOOGLE_API_KEY')], max_length=50, unique=True)),
                ('key_value', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key_store',
                'ordering': ['key_name'],
            },
        ),
    ]
