# Generated by Django 5.0.14 on 2026-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quota_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
