# Generated by Django 5.0.14 on 2026-07-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='reports.generatedreport')),
            ],
            options={
                'db_table': 'shared_link',
                'indexes': [models.Index(fields=['token'], name='shared_link_token_557b38_idx')],
            },
        ),
    ]
