"""
PDF generation engine using FPDF2.
Generates professional PDF reports with cover pages, custom branding, and Markdown rendering.
"""
import os
import re
import tempfile
import urllib.request
from urllib.parse import urlparse
from fpdf import FPDF
from django.conf import settings


class PDFExporter:
    """
    Export Markdown research reports to professional PDFs.
    Cross-platform: uses built-in fonts (no system font dependencies).
    """
    
    def __init__(self):
        self.pdf = None
    
    def _hex_to_rgb(self, hex_color: str) -> tuple:
        """Convert hex color to RGB tuple."""
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    
    def export(
        self,
        markdown_content: str,
        title: str,
        query: str,
        accent_color: str = "#3B82F6",
        logo_url: str = None,
        output_path: str = None
    ) -> str:
        """
        Export Markdown content to PDF.
        
        Args:
            markdown_content: Markdown text to render
            title: Report title
            query: Original research query
            accent_color: Hex color for branding
            logo_url: URL or path to logo image
            output_path: Where to save the PDF
            
        Returns:
            Path to generated PDF file
        """
        self.pdf = FPDF()
        self.accent_rgb = self._hex_to_rgb(accent_color)
        
        # FIXED: Use FPDF built-in fonts (Helvetica, Times, Courier)
        # These work cross-platform without system font files
        self.pdf.set_auto_page_break(auto=True, margin=20)
        
        # Cover page
        self._add_cover_page(title, query, logo_url)
        
        # Content pages
        self._add_content(markdown_content)
        
        # Save
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            self.pdf.output(output_path)
            return output_path
        
        return None
    
    def _add_cover_page(self, title: str, query: str, logo_url: str = None):
        """Add professional cover page."""
        self.pdf.add_page()
        
        # Accent bar at top
        self.pdf.set_fill_color(*self.accent_rgb)
        self.pdf.rect(0, 0, 210, 15, 'F')
        
        # Logo (if available) - FIXED: handles both local and remote URLs
        if logo_url:
            logo_path = self._resolve_logo(logo_url)
            if logo_path:
                try:
                    self.pdf.image(logo_path, x=80, y=30, w=50)
                except Exception:
                    pass  # Silently skip if logo can't be loaded
        
        # Title
        self.pdf.set_y(80)
        self.pdf.set_font('Helvetica', 'B', 24)
        self.pdf.set_text_color(*self.accent_rgb)
        self.pdf.cell(0, 15, 'AI Research Report', align='C')
        self.pdf.ln(10)
        
        # Query
        self.pdf.set_font('Helvetica', '', 12)
        self.pdf.set_text_color(80, 80, 80)
        self.pdf.multi_cell(0, 8, f'Query: {query}', align='C')
        self.pdf.ln(20)
        
        # Date
        from datetime import datetime
        self.pdf.set_font('Helvetica', '', 10)
        self.pdf.cell(0, 10, f'Generated: {datetime.now().strftime("%B %d, %Y")}', align='C')
        
        # Footer line
        self.pdf.set_y(270)
        self.pdf.set_draw_color(*self.accent_rgb)
        self.pdf.line(20, 270, 190, 270)
        self.pdf.set_font('Helvetica', '', 8)
        self.pdf.set_text_color(150, 150, 150)
        self.pdf.cell(0, 10, 'Generated by AI Research Agent', align='C')
    
    def _resolve_logo(self, logo_url: str) -> str:
        """
        Resolve logo URL to a local file path.
        Downloads remote URLs to temp file, returns local paths as-is.
        
        Args:
            logo_url: URL or local path to logo image
            
        Returns:
            Local file path or None if unavailable
        """
        if not logo_url:
            return None
        
        # Local absolute path
        if logo_url.startswith('/'):
            # Check if it's a media file
            if logo_url.startswith(settings.MEDIA_URL):
                relative_path = logo_url[len(settings.MEDIA_URL):]
                local_path = os.path.join(settings.MEDIA_ROOT, relative_path)
                return local_path if os.path.exists(local_path) else None
            
            # Check static files
            if logo_url.startswith(settings.STATIC_URL):
                relative_path = logo_url[len(settings.STATIC_URL):]
                for static_dir in settings.STATICFILES_DIRS:
                    local_path = os.path.join(static_dir, relative_path)
                    if os.path.exists(local_path):
                        return local_path
                return None
            
            # Raw absolute path
            return logo_url if os.path.exists(logo_url) else None
        
        # Remote URL - download to temp file
        if logo_url.startswith(('http://', 'https://')):
            try:
                parsed = urlparse(logo_url)
                suffix = os.path.splitext(parsed.path)[1] or '.png'
                
                # Create temp file that persists until process ends
                with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
                    urllib.request.urlretrieve(logo_url, tmp.name)
                    return tmp.name
            except Exception:
                return None
        
        # Relative path - check media root
        local_path = os.path.join(settings.MEDIA_ROOT, logo_url)
        if os.path.exists(local_path):
            return local_path
        
        return None
    
    def _add_content(self, markdown_content: str):
        """Parse and render Markdown content."""
        self.pdf.add_page()
        self.pdf.set_auto_page_break(auto=True, margin=20)
        
        lines = markdown_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                self.pdf.ln(4)
                continue
            
            # Headers
            if line.startswith('# '):
                self.pdf.set_font('Helvetica', 'B', 18)
                self.pdf.set_text_color(*self.accent_rgb)
                self.pdf.cell(0, 12, line[2:], ln=True)
                self.pdf.set_draw_color(*self.accent_rgb)
                self.pdf.line(20, self.pdf.get_y(), 190, self.pdf.get_y())
                self.pdf.ln(4)
            
            elif line.startswith('## '):
                self.pdf.set_font('Helvetica', 'B', 14)
                self.pdf.set_text_color(50, 50, 50)
                self.pdf.cell(0, 10, line[3:], ln=True)
                self.pdf.ln(2)
            
            elif line.startswith('### '):
                self.pdf.set_font('Helvetica', 'B', 12)
                self.pdf.set_text_color(70, 70, 70)
                self.pdf.cell(0, 8, line[4:], ln=True)
            
            # Horizontal rule
            elif line.startswith('---'):
                self.pdf.ln(4)
                self.pdf.set_draw_color(200, 200, 200)
                self.pdf.line(20, self.pdf.get_y(), 190, self.pdf.get_y())
                self.pdf.ln(4)
            
            # List items
            elif line.startswith('- ') or line.startswith('* '):
                self.pdf.set_font('Helvetica', '', 10)
                self.pdf.set_text_color(50, 50, 50)
                self.pdf.set_x(25)
                self.pdf.cell(5, 6, chr(149), ln=0)
                self._render_rich_text(line[2:], x=30)
                self.pdf.ln(6)
            
            # Numbered list
            elif re.match(r'^\d+\.\s', line):
                self.pdf.set_font('Helvetica', '', 10)
                self.pdf.set_text_color(50, 50, 50)
                match = re.match(r'^(\d+)\.\s(.*)', line)
                if match:
                    num, text = match.groups()
                    self.pdf.set_x(25)
                    self.pdf.cell(8, 6, f'{num}.', ln=0)
                    self._render_rich_text(text, x=33)
                self.pdf.ln(6)
            
            # Regular paragraph
            else:
                self.pdf.set_font('Helvetica', '', 10)
                self.pdf.set_text_color(50, 50, 50)
                self._render_rich_text(line, x=20)
                self.pdf.ln(6)
    
    def _render_rich_text(self, text: str, x: float = 20):
        """Render text with bold and italic Markdown formatting."""
        self.pdf.set_x(x)
        
        # Parse inline formatting
        parts = re.split(r'(\*\*.*?\*\*|\*.*?\*|\[.*?\]\(.*?\))', text)
        
        for part in parts:
            if not part:
                continue
            
            # Bold **text**
            if part.startswith('**') and part.endswith('**'):
                self.pdf.set_font('Helvetica', 'B', 10)
                self.pdf.write(6, part[2:-2])
            
            # Italic *text*
            elif part.startswith('*') and part.endswith('*') and not part.startswith('**'):
                self.pdf.set_font('Helvetica', 'I', 10)
                self.pdf.write(6, part[1:-1])
            
            # Links [text](url)
            elif re.match(r'\[.*?\]\(.*?\)', part):
                match = re.match(r'\[(.*?)\]\((.*?)\)', part)
                if match:
                    link_text, url = match.groups()
                    self.pdf.set_font('Helvetica', 'U', 10)
                    self.pdf.set_text_color(0, 0, 255)
                    self.pdf.write(6, link_text, link=url)
                    self.pdf.set_text_color(50, 50, 50)
            
            # Plain text
            else:
                self.pdf.set_font('Helvetica', '', 10)
                self.pdf.write(6, part)