# Generated by Django 5.0.14 on 2026-07-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query_pattern', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_template',
                'ordering': ['-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='research_te_user_id_c34e26_idx'), models.Index(fields=['is_public'], name='research_te_is_publ_6aae4a_idx')],
            },
        ),
    ]
