# Generated by Django 5.0.14 on 2026-07-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('cover_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='research.researchquery')),
            ],
            options={
                'db_table': 'generated_report',
            },
        ),
    ]
