# Generated by Django 5.0.14 on 2026-07-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('search_depth', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='advanced', max_length=10)),
                ('max_results', models.IntegerField(default=5)),
                ('llm_model', models.CharField(choices=[('groq', 'Groq (Llama 3.3)'), ('gemini', 'Google Gemini')], default='groq', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('final_insight', models.TextField(blank=True, null=True)),
                ('raw_sources', models.JSONField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_query',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='research_qu_user_id_12ab64_idx'), models.Index(fields=['created_at'], name='research_qu_created_23e750_idx')],
            },
        ),
    ]
