# Generated by Django 5.0.14 on 2026-07-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.researchquery')),
            ],
            options={
                'db_table': 'research_source',
                'ordering': ['-relevance_score'],
                'indexes': [models.Index(fields=['query'], name='research_so_query_i_d0d2fc_idx')],
            },
        ),
    ]
