# Generated by Django 5.0.14 on 2026-07-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='parent_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='research.researchquery'),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='researchquery',
            index=models.Index(fields=['parent_query', 'is_latest'], name='research_qu_parent__711879_idx'),
        ),
    ]
